- module: postgresql
  metricsets:
   - database
   - bgwriter
   - activity
   - statement
  period: 10s
  hosts: ["postgres://postgres:5432?sslmode=disable"]
  username: postgres
  password: somepassword
