version: '3.5'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: somepassword
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - ./postgres/postgresql.docker.conf:/etc/postgresql/postgresql.conf
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pglogs:/var/log/postgresql/:rw
      - /mnt/disks/pgsql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - smurf

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - smurf

  portainer:
    image: portainer/portainer:latest
    restart: always
    command: --admin-password $$2y$$05$$kji3RS35ikVlkxY0eJFn.uAko8nSqGr/ZvFyPYefiwJzHd0aOmY5O
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    volumes:
      - esdata:/usr/share/elasticsearch/data:rw
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      cluster.name: "smurf-cluster"
      network.host: 0.0.0.0
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      xpack.security.enabled: false
      discovery.type: single-node
    networks:
      - smurf

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    environment:
      server.name: kibana
      server.host: 0
      elasticsearch.hosts: "http://elasticsearch:9200"
    ports:
      - "5601:5601"
    networks:
      - smurf
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.6.2
    user: root
    restart: always
    environment:
      - strict.perms=false
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    volumes:
      - ./filebeat/config/filebeat.reference.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./filebeat/config/postgresql.yml:/usr/share/filebeat/modules.d/postgres.yml:ro
      - pglogs:/var/log/postgresql/:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - smurf
    depends_on:
      - postgres
      - kibana
      - elasticsearch

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.6.2
    user: root
    restart: always
    volumes:
      - ./metricbeat/config/metricbeat.reference.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - ./metricbeat/config/postgresql.yml:/usr/share/metricbeat/modules.d/postgresql.yml:ro
      - ./metricbeat/config/docker.yml:/usr/share/metricbeat/modules.d/docker.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - smurf
    depends_on:
      - postgres
      - kibana
      - elasticsearch

volumes:
  esdata:
    driver: local
  pglogs:
    driver: local

networks:
  smurf:
    driver: bridge
    name: smurf
